[project]
name = "LOVEBrew"
description = "A web application to build your LOVE Potion projects"
requires-python = ">=3.10"
dependencies = ["selenium", "selenium-requests", "pytest"]
version = "0.1.0"
